# Generated by Django 2.2.6 on 2021-07-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sender', models.CharField(max_length=128)),
                ('receiver', models.CharField(max_length=128)),
                ('postdate', models.SmallIntegerField()),
                ('status', models.CharField(choices=[('D', 'draft'), ('P', 'published')], default='D', max_length=10)),
            ],
        ),
    ]
